server {
    listen 80;                 # ← уже есть
    listen [::]:80;            # ← Должно быть! (добавь, если нет)
    server_name plywoodmarket.ru www.plywoodmarket.ru;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        auth_basic off;
        access_log off;
        try_files $uri =404;
    }

    location / { return 301 https://$host$request_uri; }
}